In [1]:

from transformers import AutoModelForSequenceClassification, AutoTokenizer
import pandas as pd
import numpy as np
import torch
import seaborn as sns
from datasets import load_dataset
from datasets import DatasetDict
import datasets

In [2]:
from huggingface_hub import notebook_login
notebook_login()

#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

In [4]:

from transformers import AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding
from torch.utils.data import DataLoader

n_categories=18


BASE_MODEL = "distilbert-base-uncased"
LEARNING_RATE = 5e-5
MAX_LENGTH = 128
BATCH_SIZE = 4
EPOCHS = 3
id2label = {k:k for k in range(n_categories)}
label2id = {k:k for k in range(n_categories)}


tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
model = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL,id2label=id2label, label2id=label2id)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_projector.weight', 'vocab_transform.bias', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.weight', 'pre_classifier.bias', 'classi

In [5]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0): TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
       

In [31]:
dataset_6k_train = load_dataset('csv', data_files='train_4bins_6k_untailored_seq.csv')
dataset_6k_train=dataset_6k_train['train']
dataset_6k_validation=dataset_6k_train.train_test_split(test_size=0.1, shuffle=True)['test']

dataset_full_train=[load_dataset('csv', data_files='train_all_untailored_seq.csv')]
dataset_full_train=dataset_full_train[0]['train']




Using custom data configuration default-f0a5ffb0335c563c
Reusing dataset csv (/home/lu/.cache/huggingface/datasets/csv/default-f0a5ffb0335c563c/0.0.0/51cce309a08df9c4d82ffd9363bbe090bf173197fc01a71b034e8594995a1a58)


  0%|          | 0/1 [00:00<?, ?it/s]

Using custom data configuration default-e252b1b23be6881c
Reusing dataset csv (/home/lu/.cache/huggingface/datasets/csv/default-e252b1b23be6881c/0.0.0/51cce309a08df9c4d82ffd9363bbe090bf173197fc01a71b034e8594995a1a58)


  0%|          | 0/1 [00:00<?, ?it/s]

In [33]:
dataset_6k_train

Dataset({
    features: ['Sequence', 'Exp'],
    num_rows: 24000
})

In [34]:
dataset_6k_validation

Dataset({
    features: ['Sequence', 'Exp'],
    num_rows: 2400
})

In [35]:
dataset_full_train

Dataset({
    features: ['Sequence', 'Exp'],
    num_rows: 6739258
})

In [38]:
dataset_6k=DatasetDict()
dataset_6k['train']=dataset_6k_train
dataset_6k['test']=dataset_6k_validation

In [39]:
dataset_6k

DatasetDict({
    train: Dataset({
        features: ['Sequence', 'Exp'],
        num_rows: 24000
    })
    test: Dataset({
        features: ['Sequence', 'Exp'],
        num_rows: 2400
    })
})

In [41]:
from re import findall
import itertools  
def textProcess(s,k,fill=' '):
  return ' '.join(map(''.join, itertools.zip_longest(*[iter(s)]*k, fillvalue=fill)))

In [42]:


def preprocess_function(examples):
    text=examples['Sequence']
    label=examples['Exp']
    text=textProcess(text,1)
    examples["text"]=text
    examples = tokenizer(text, truncation=True, padding="max_length", max_length=MAX_LENGTH)
    # Change this to real number
    if float(label)>=0:
      examples["label"] = int(round(float(label)))
    else:
      examples["label"] = float(label)

    return examples

for split in dataset_6k:
    dataset_6k[split] = dataset_6k[split].map(preprocess_function,num_proc=4)

#0:   0%|          | 0/6000 [00:00<?, ?ex/s]

#1:   0%|          | 0/6000 [00:00<?, ?ex/s]

#2:   0%|          | 0/6000 [00:00<?, ?ex/s]

#3:   0%|          | 0/6000 [00:00<?, ?ex/s]

#0:   0%|          | 0/600 [00:00<?, ?ex/s]

#1:   0%|          | 0/600 [00:00<?, ?ex/s]

#2:   0%|          | 0/600 [00:00<?, ?ex/s]

#3:   0%|          | 0/600 [00:00<?, ?ex/s]

KeyError: 'train'

In [ ]:
!nvidia-smi -L

In [44]:

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from datasets import load_metric
import numpy as np
from scipy import stats
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score



def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    metric = load_metric("accuracy")
    accuracy=metric.compute(predictions=predictions, references=labels)


    # finally, compute metrics
    y_true = labels
    y_pred=predictions

    print(y_true,y_pred)
    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
    accuracy = accuracy_score(y_true, y_pred)
    # return as dictionary
    from scipy import stats
    pearsonr=(stats.spearmanr(y_true, y_pred))[0]
    spearmanr=(stats.pearsonr(y_true, y_pred))[0]
    metrics = {'f1': f1_micro_average,
               'accuracy': accuracy,
               'pearsonr': pearsonr,
               'spearmanr':spearmanr,
               
               }
    return metrics




In [47]:
from transformers import TrainingArguments
from transformers import Trainer

EPOCHS = 3
BATCH_SIZE=16
training_args = TrainingArguments(
    f"zluvolyote/DEREXP_home_6k_each",
    report_to=None,
    save_total_limit=3,
    learning_rate=LEARNING_RATE,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS,
    evaluation_strategy="steps",
    save_strategy="steps",
    metric_for_best_model="spearmanr",
    load_best_model_at_end=True,)



In [48]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_6k["train"],
    eval_dataset=dataset_6k["test"],
    compute_metrics=compute_metrics,
)



In [ ]:
from tqdm import tqdm_notebook

#563f1d7442f85354fb487aef1a822fe4899341b0
trainer.train()

The following columns in the training set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
/home/lu/.local/lib/python3.10/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 24000
  Num Epochs = 3
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 4500
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
wandb: Currently logged in as: luzhixu0

The following columns in the evaluation set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 2400
  Batch size = 16


[ 5  8  5 ...  4 13 15] [ 8 15 10 ...  8 15 15]


Saving model checkpoint to zluvolyote/DEREXP_home_6k_each/checkpoint-500
Configuration saved in zluvolyote/DEREXP_home_6k_each/checkpoint-500/config.json
Model weights saved in zluvolyote/DEREXP_home_6k_each/checkpoint-500/pytorch_model.bin
The following columns in the evaluation set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 2400
  Batch size = 16


[ 5  8  5 ...  4 13 15] [ 8 15  8 ...  8 15 15]


Saving model checkpoint to zluvolyote/DEREXP_home_6k_each/checkpoint-1000
Configuration saved in zluvolyote/DEREXP_home_6k_each/checkpoint-1000/config.json
Model weights saved in zluvolyote/DEREXP_home_6k_each/checkpoint-1000/pytorch_model.bin
The following columns in the evaluation set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 2400
  Batch size = 16


[ 5  8  5 ...  4 13 15] [ 8 11 11 ...  8 15 15]


Saving model checkpoint to zluvolyote/DEREXP_home_6k_each/checkpoint-1500
Configuration saved in zluvolyote/DEREXP_home_6k_each/checkpoint-1500/config.json
Model weights saved in zluvolyote/DEREXP_home_6k_each/checkpoint-1500/pytorch_model.bin
The following columns in the evaluation set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 2400
  Batch size = 16


[ 5  8  5 ...  4 13 15] [ 8 11 11 ...  8 15 15]


Saving model checkpoint to zluvolyote/DEREXP_home_6k_each/checkpoint-2000
Configuration saved in zluvolyote/DEREXP_home_6k_each/checkpoint-2000/config.json
Model weights saved in zluvolyote/DEREXP_home_6k_each/checkpoint-2000/pytorch_model.bin
Deleting older checkpoint [zluvolyote/DEREXP_home_6k_each/checkpoint-500] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `DistilBertForSequenceClassification.forward` and have been ignored: text, Exp, Sequence. If text, Exp, Sequence are not expected by `DistilBertForSequenceClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 2400
  Batch size = 16


[ 5  8  5 ...  4 13 15] [ 7 11 11 ...  8 15 15]


Saving model checkpoint to zluvolyote/DEREXP_home_6k_each/checkpoint-2500
Configuration saved in zluvolyote/DEREXP_home_6k_each/checkpoint-2500/config.json
Model weights saved in zluvolyote/DEREXP_home_6k_each/checkpoint-2500/pytorch_model.bin
Deleting older checkpoint [zluvolyote/DEREXP_home_6k_each/checkpoint-1000] due to args.save_total_limit


In [ ]:
trainer.eval_dataset=dataset["test"]
trainer.evaluate()

In [ ]:
def predictFromText(text):
  encoded = tokenizer(text, truncation=True, padding="max_length", max_length=128, return_tensors="pt").to('cuda')
  logits = model(**encoded).logits
  return torch.argmax(logits, axis=1).to('cpu').detach().numpy()

In [ ]:

from scipy import stats
print(stats.spearmanr(predicted,labels))

print(stats.pearsonr(predicted,labels))

In [ ]:
import os
os.environ['WANDB_SILENT']="true"
dataset_raw= load_dataset("zluvolyote/DreamNLP")

In [ ]:

def preprocess_function(examples):
    text=examples['Sequence']
    label=examples['Exp']
    text=textProcess(text,1)
    examples["text"]=text
    examples = tokenizer(text, truncation=True, padding="max_length", max_length=MAX_LENGTH)
    # Change this to real number
    if float(label)>=0:
      examples["label"] = int(round(float(label)))
    else:
      examples["label"] = float(label)

    return examples

for split in dataset_raw:
    dataset_raw[split] = dataset_raw[split].map(preprocess_function,num_proc=8)

In [ ]:
predicted=[]
labels=[]

testSet = dataset_raw['train']
cnt=0
for entry in testSet:
    text=entry['text']
    label=entry['label']
    labels.append(label)
    # Change this to real number.cpu()
    pred=predictFromText(text)
    cnt+=1
    if(cnt%1000)==0:
        print(cnt/len(dataset_raw['train']))
    predicted.append(pred[0])

In [ ]:
from torch.utils import data
import pandas as pd
df=pd.DataFrame()
df['Seq']=dataset['train']['Sequence']
df['Predicted_Exp']=predicted

df['Actual_Exp']=labels

In [ ]:
df.head()

In [ ]:

df.to_csv('predict_75_10k_train.csv')
